#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Yarn
export PATH="$PATH:`yarn global bin`"

function fzf_vim () {
  nvim $(fzf --preview 'bat --color=always {} | head -500')
}

# NeoVim
alias nvim=fzf_vim
alias vim=nvim
alias vi=nvim
alias vimdiff='nvim -d'

# FZF
# --files: List files that would be searched but do not search
# --hidden: Search hidden files and folders
# --smart-case: Searches case insensitively if the pattern is all lowercase. Search case sensitively otherwise.
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --hidden --smart-case --follow --glob "!.git/*"'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

# Hub
eval "$(hub alias -s)"


# Gcloud
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
